# Generated by Django 6.0.5 on 2026-06-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_deal_stage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_new_lead',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_task_deadline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_workspace_updates',
            field=models.BooleanField(default=True),
        ),
    ]
