# Generated by Django 6.0.5 on 2026-06-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_notify_deal_stage_user_notify_new_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], db_index=True, default='staff', max_length=20),
        ),
    ]
