# Generated by Django 6.0.5 on 2026-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teaminvitation_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_team',
            field=models.BooleanField(default=False, help_text='Grant team management access to this staff member.'),
        ),
    ]
