# Generated by Django 6.0.5 on 2026-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_country_user_enable_google_calendar_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_notifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
