# Generated by Django 6.0.5 on 2026-06-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_email_notifications_user_push_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Primary Admin'), ('manager', 'Secondary Admin'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Primary Admin'), ('manager', 'Secondary Admin'), ('staff', 'Staff'), ('customer', 'Customer')], db_index=True, default='staff', max_length=20),
        ),
    ]
