# Generated by Django 6.0.5 on 2026-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teaminvitation_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether this user has two-factor authentication enabled.'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('email', 'Email Code'), ('google_authenticator', 'Google Authenticator')], default='disabled', help_text='The preferred method for two-factor authentication.', max_length=30),
        ),
    ]
