# Generated by Django 6.0.5 on 2026-06-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_two_factor_enabled_user_two_factor_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='The base32 secret key used for two-factor authentication.', max_length=64, null=True),
        ),
    ]
