# Generated by Django 6.0.5 on 2026-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_email_code',
            field=models.CharField(blank=True, help_text='The temporary code sent via email for two-factor verification.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_email_code_created',
            field=models.DateTimeField(blank=True, help_text='The timestamp when the temporary email code was generated.', null=True),
        ),
    ]
