# Generated by Django 6.0.5 on 2026-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teaminvitation_department_teaminvitation_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
