# Generated by Django 6.0.5 on 2026-07-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_emergency_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(default='staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='staff', max_length=50),
        ),
    ]
