# Generated by Django 6.0.5 on 2026-08-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_duplicate_afthab'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvitation',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee ID or code.', max_length=100, null=True),
        ),
    ]
