# Generated by Django 6.0.5 on 2026-09-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('deal_won', 'Deal Won'), ('task_due', 'Task Due'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_upgraded', 'Subscription Upgraded'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('general', 'General')], db_index=True, default='general', max_length=40),
        ),
    ]
