"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / '.env'


def load_env_file(env_file):
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()

        if value and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        os.environ.setdefault(key, value)


def env(name, default=None):
    return os.environ.get(name, default)


def env_bool(name, default=False):
    value = env(name)
    if value is None:
        return default

    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name, default):
    value = env(name)
    if value is None:
        return default

    return int(value)


def env_list(name, default=None):
    value = env(name)
    if value is None:
        return default[:] if default else []

    return [item.strip() for item in value.split(',') if item.strip()]


load_env_file(ENV_FILE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', 'unsafe-dev-secret-key-change-me')

# H1 fix: Default DEBUG to False — must explicitly set DEBUG=True in dev .env
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

# H2 fix: Fail loudly if SECRET_KEY is not set in production
if not DEBUG and SECRET_KEY == 'unsafe-dev-secret-key-change-me':
    raise RuntimeError(
        "SECRET_KEY must be set to a strong random value in production. "
        "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(64))\""
    )

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', ['127.0.0.1', 'localhost', 'lumeo-crm-backend.onrender.com', 'lumeo.estgrp.in'])
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.estgrp\.in$",
    r"^http://localhost:.*$",
    r"^http://127\.0\.0\.1:.*$",
]
CSRF_TRUSTED_ORIGINS = [
    'https://lumeo-crm-exjs.vercel.app',
    'https://lumeo.estgrp.in',
    'https://lumeo-crm-backend.onrender.com',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# Razorpay Subscription Credentials
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', 'rzp_test_placeholder_key_id')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', 'placeholder_key_secret')
# C3 fix: HMAC secret for webhook signature verification (set this in Razorpay Dashboard → Webhooks)
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET', '')

# Frontend URL used for building invite links (H8 fix)
FRONTEND_URL = env('FRONTEND_URL', 'http://localhost:3000')

# ── Production security (auto-enabled when DEBUG=False) ──────────────────────
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'DENY'



# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'django_filters',
    'axes',               # Rate limiting + login lockout
    'companies',
    'accounts',
    'crm',
    'subscriptions',
    'notifications',
    'attendance',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # AxesMiddleware must be LAST so it can intercept failed logins
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', 'crm_saas'),
        'USER': env('DB_USER', 'postgres'),
        'PASSWORD': env('DB_PASSWORD', ''),
        'HOST': env('DB_HOST', 'localhost'),
        'PORT': env('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Cookie-based JWT auth first (browser clients)
        # Falls back to Authorization: Bearer header for API clients
        'accounts.cookie_auth.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': env_int('API_PAGE_SIZE', 20),
    # DRF throttling for the login endpoint (defence-in-depth alongside axes)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',   # Max 10 login attempts per minute per IP
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env_int('ACCESS_TOKEN_MINUTES', 30)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int('REFRESH_TOKEN_DAYS', 7)),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# C2 fix: lock down CORS — only allow listed origins, never all origins in production
CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', False)

# CRITICAL: Must be True when frontend uses withCredentials:true (HttpOnly cookie auth)
# Without this the browser rejects the response even when OPTIONS preflight passes.
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    [
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:3001',  # fallback port when 3000 is taken
        'http://localhost:3001',
        'http://127.0.0.1:3002',
        'http://localhost:3002',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
        'https://lumeo-crm-backend.onrender.com',
        'https://lumeo.estgrp.in',
    ]
)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    [
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:3001',
        'http://localhost:3001',
        'http://127.0.0.1:3002',
        'http://localhost:3002',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
        'https://lumeo-crm-backend.onrender.com',
        'https://lumeo.estgrp.in',
    ]
)

import ssl
REDIS_URL = env('REDIS_URL', 'redis://127.0.0.1:6379/1')
if REDIS_URL.startswith('rediss://') and 'ssl_cert_reqs' not in REDIS_URL:
    REDIS_URL += ('&ssl_cert_reqs=none' if '?' in REDIS_URL else '?ssl_cert_reqs=none')

CELERY_BROKER_URL = env('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', REDIS_URL)

if CELERY_BROKER_URL.startswith('rediss://'):
    CELERY_BROKER_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}
if CELERY_RESULT_BACKEND.startswith('rediss://'):
    CELERY_REDIS_BACKEND_USE_SSL = {'ssl_cert_reqs': ssl.CERT_NONE}

# C7 fix: Default to True — ensures emails execute synchronously and reliably without requiring a separate active Celery worker service in production.
# Set CELERY_TASK_ALWAYS_EAGER=False in your live .env only if you have an active dedicated Celery worker service running.
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', True)


# ── django-axes: brute-force protection ────────────────────────────────────

# Top solution: Never lock out an entire IP address (prevents blocking admins/coworkers on the same IP)
AXES_ONLY_USER_FAILURES = True
AXES_LOCKOUT_PARAMETERS = ['username']
AXES_FAILURE_LIMIT = 20
# Set cooloff to 1 minute so any existing lockouts immediately expire and unlock the user
AXES_COOLOFF_TIME = timedelta(minutes=1)
AXES_RESET_ON_SUCCESS = True
AXES_BACKEND = 'axes.backends.AxesBackend'

AUTHENTICATION_BACKENDS = [
    # axes must come FIRST to intercept locked-out users
    'axes.backends.AxesStandaloneBackend',
    'accounts.backends.EmailOrUsernameModelBackend',
]


EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if not DEBUG else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', 'localhost')
EMAIL_PORT = env_int('EMAIL_PORT', 25)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', False)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)    # For Resend port 465
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 5)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'noreply@crm-saas.local')
ADMIN_NOTIFICATION_EMAIL = env('ADMIN_NOTIFICATION_EMAIL', 'support@crm.estgrp.in')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = env('TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serve compressed static files with far-future cache headers
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# trigger reload

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Razorpay Configuration
RAZORPAY_KEY_ID = env('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = env('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = env('RAZORPAY_WEBHOOK_SECRET', '')
