# Generated by Django 6.0.5 on 2026-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(db_index=True, default='monthly', max_length=20),
        ),
    ]
