# Generated by Django 6.0.5 on 2026-05-18 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_currency_company_domain'),
        ('crm', '0005_invoice_invoicelineitem_quote_quotelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('lead', 'Lead'), ('customer', 'Customer'), ('deal', 'Deal')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date')], default='text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='companies.company')),
            ],
            options={
                'ordering': ('label',),
                'unique_together': {('company', 'model_name', 'name')},
            },
        ),
    ]
