# Generated by Django 6.0.5 on 2026-05-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_currency_company_domain'),
        ('crm', '0006_customer_custom_data_deal_custom_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('deal_won', 'Deal Stage = Won'), ('deal_lost', 'Deal Stage = Lost'), ('lead_qualified', 'Lead Status = Qualified')], max_length=50)),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('send_notification', 'Send Notification')], max_length=50)),
                ('action_payload', models.JSONField(blank=True, default=dict, help_text="Configuration payload (e.g., {'task_title': '...', 'due_days_offset': 3})")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='companies.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
