# Generated by Django 6.0.5 on 2026-05-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_currency_company_domain'),
        ('crm', '0007_workflowrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ('row_order', '-created_at')},
        ),
        migrations.AddField(
            model_name='deal',
            name='row_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'row_order'], name='crm_deal_company_439f8b_idx'),
        ),
    ]
