# Generated by Django 6.0.5 on 2026-05-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_emailtemplate_smtpconfig_webhooksubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smtpconfig',
            options={'ordering': ('id',)},
        ),
    ]
