# Generated by Django 6.0.5 on 2026-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_smtpconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
