# Generated by Django 6.0.5 on 2026-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_bookinglink_calendaraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.IntegerField(blank=True, help_text='AI generated lead score (1-100)', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='score_rationale',
            field=models.TextField(blank=True, help_text='AI rationale for the score', null=True),
        ),
    ]
