# Generated by Django 6.0.5 on 2026-06-19 09:13

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_company_allow_client_signup_and_more'),
        ('crm', '0020_order_orderitem_event_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='task',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='WorkflowSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_qualified', 'Lead Qualified')], max_length=50)),
                ('stop_on_statuses', models.JSONField(blank=True, default=crm.models.default_workflow_sequence_stop_statuses, help_text='Lead statuses that should stop active runs for this sequence.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_sequences', to='companies.company')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lead', 'Lead'), ('deal', 'Deal'), ('customer', 'Customer')], max_length=50)),
                ('record_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], db_index=True, default='active', max_length=20)),
                ('stop_reason', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='companies.company')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crm.workflowsequence')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay after the previous step before this step becomes due.')),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('send_notification', 'Send Notification'), ('send_email', 'Send Email')], max_length=50)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='crm.emailtemplate')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crm.workflowsequence')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_step_runs', to='companies.company')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='crm.workflowrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='crm.workflowstep')),
            ],
            options={
                'ordering': ('due_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='workflow_step_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.workflowsteprun'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['company', 'status'], name='crm_workflo_company_ad0385_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['company', 'record_type', 'record_id'], name='crm_workflo_company_7d5ff1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('sequence', 'order')},
        ),
        migrations.AddIndex(
            model_name='workflowsteprun',
            index=models.Index(fields=['company', 'status', 'due_at'], name='crm_workflo_company_9c0867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowsteprun',
            unique_together={('run', 'step')},
        ),
    ]
