# Generated by Django 6.0.5 on 2026-06-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_task_customer_task_deal_task_lead_workflowsequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaraccount',
            name='buffer_minutes',
            field=models.IntegerField(default=15, help_text='Buffer time between booked events in minutes.'),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='location_type',
            field=models.CharField(default='google_meet', help_text='Default meeting medium (e.g. google_meet, zoom, phone, custom).', max_length=50),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='minimum_notice_hours',
            field=models.IntegerField(default=4, help_text='Minimum notice required before booking in hours.'),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='sync_conflicts',
            field=models.BooleanField(default=True, help_text='Check this calendar for conflicts.'),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='working_hours_end',
            field=models.CharField(default='17:00', help_text='Daily availability end time (HH:MM).', max_length=5),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='working_hours_start',
            field=models.CharField(default='09:00', help_text='Daily availability start time (HH:MM).', max_length=5),
        ),
        migrations.AddField(
            model_name='calendaraccount',
            name='write_events',
            field=models.BooleanField(default=True, help_text='Add booked meetings to this calendar.'),
        ),
    ]
