# Generated by Django 6.0.5 on 2026-07-02 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_calendaraccount_buffer_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='crm.customer'),
        ),
    ]
