# Generated by Django 6.0.5 on 2026-07-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_invoice_status_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
