# Generated by Django 6.0.5 on 2026-07-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_lead_mobile_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(db_index=True, default='prospect', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(db_index=True, default='new', max_length=50),
        ),
    ]
