# Generated by Django 6.0.5 on 2026-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_deal_stage_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('connected', 'Connected'), ('not_connected', 'Not Connected')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='call_reason',
            field=models.CharField(blank=True, choices=[('no_answer', 'No Answer'), ('switched_off', 'Switched Off'), ('busy', 'Busy'), ('wrong_number', 'Wrong Number'), ('invalid_number', 'Invalid Number'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
    ]
