# Generated by Django 6.0.5 on 2026-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_activity_call_outcome_activity_call_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
