# Generated by Django 6.0.5 on 2026-07-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_activity_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
