# Generated by Django 6.0.5 on 2026-07-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_invoicelineitem_hsn_sac_code_orderitem_hsn_sac_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
