# Generated by Django 6.0.5 on 2026-07-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_invoice_notes_invoice_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, help_text='3-letter currency code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, help_text='3-letter currency code', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(blank=True, help_text='3-letter currency code', max_length=3, null=True),
        ),
    ]
