# Generated by Django 6.0.5 on 2026-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_invoice_currency_order_currency_quote_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
