# Generated by Django 6.0.5 on 2026-07-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0056_invoicesettings_bank_account_name_and_more'),
        ('crm', '0033_invoicelineitem_unit_product_unit_quotelineitem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='companies.company')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crm.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['company', 'name'], name='crm_service_company_e3360b_idx'),
        ),
    ]
