# Generated by Django 6.0.5 on 2026-07-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_servicecategory_lead_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
