# Generated by Django 6.0.5 on 2026-07-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_timesheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('row_order', 'due_date', 'title')},
        ),
        migrations.AddField(
            model_name='task',
            name='row_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
