# Generated by Django 6.0.5 on 2026-07-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_alter_task_options_task_row_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='content',
            field=models.TextField(blank=True, help_text='HTML content of the contract/proposal'),
        ),
    ]
