# Generated by Django 6.0.5 on 2026-08-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_quote_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If True, the quote is read-only'),
        ),
    ]
