# Generated by Django 6.0.5 on 2026-08-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_quote_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deal',
            field=models.ForeignKey(blank=True, help_text='The deal this lead was converted into or is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.deal'),
        ),
    ]
