# Generated by Django 6.0.5 on 2026-08-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_activity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm.project'),
        ),
    ]
