# Generated by Django 6.0.5 on 2026-08-06 09:53

from django.db import migrations


def calculate_item_totals(apps, schema_editor):
    PurchaseOrderItem = apps.get_model('crm', 'PurchaseOrderItem')
    BillItem = apps.get_model('crm', 'BillItem')
    
    for po_item in PurchaseOrderItem.objects.all():
        if po_item.quantity is not None and po_item.unit_price is not None:
            po_item.total = po_item.quantity * po_item.unit_price
            po_item.save(update_fields=['total'])
            
    for bill_item in BillItem.objects.all():
        if bill_item.quantity is not None and bill_item.unit_price is not None:
            bill_item.total = bill_item.quantity * bill_item.unit_price
            bill_item.save(update_fields=['total'])

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_vendor_bank_details_vendor_contact_name_and_more'),
    ]

    operations = [
        migrations.RunPython(calculate_item_totals),
    ]
