# Generated by Django 6.0.5 on 2026-08-13 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_auto_20260806_1523'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('deadline', 'Deadline'), ('leave', 'Leave'), ('review', 'Review')], default='meeting', max_length=50),
        ),
    ]
