# Generated by Django 6.0.5 on 2026-08-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_event_attendees_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
