# Generated by Django 6.0.5 on 2026-08-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_campaign_scheduled_at_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_state_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
