# Generated by Django 6.0.5 on 2026-09-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0061_company_whatsapp_access_token_and_more'),
        ('crm', '0053_emailaccount_subscription_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_revenues', to='companies.company')),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('company', 'date')},
            },
        ),
    ]
