# Generated by Django 6.0.5 on 2026-05-23 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_company_currency_company_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clock_in', models.DateTimeField(db_index=True)),
                ('clock_out', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('work_location', models.CharField(choices=[('office', 'Office'), ('wfh', 'Work From Home'), ('onsite', 'On-Site'), ('field', 'Field / Travel')], db_index=True, default='office', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-clock_in',),
            },
        ),
        migrations.CreateModel(
            name='BreakLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('time_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.timelog')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
    ]
