# Generated by Django 6.0.5 on 2026-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_leaverequest_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='is_auto_closed',
            field=models.BooleanField(default=False, help_text='True if closed by midnight sweep'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='shift_status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('overtime', 'Overtime')], db_index=True, default='on_time', max_length=20),
        ),
    ]
