# Generated by Django 6.0.5 on 2026-08-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_timelog_is_auto_closed_timelog_shift_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='deductions',
            new_name='total_deductions',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='allowances',
            new_name='total_earnings',
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payroll',
            name='earnings_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payroll',
            name='loss_of_pay_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
