# Generated by Django 6.0.5 on 2026-08-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_deductions_payroll_total_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Annual'), ('sick', 'Medical / Sick'), ('casual', 'Casual'), ('unpaid', 'Unpaid'), ('half_day', 'Half Day')], db_index=True, default='paid', max_length=20),
        ),
    ]
