# Generated by Django 6.0.5 on 2026-09-14 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_leaverequest_leave_type'),
        ('companies', '0061_company_whatsapp_access_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('content', models.TextField(blank=True, help_text='The manual daily report written by the employee.')),
                ('automated_stats', models.JSONField(blank=True, help_text='Stats captured at the time of submission', null=True)),
                ('sentiment', models.CharField(blank=True, max_length=50, null=True)),
                ('blockers', models.TextField(blank=True, null=True)),
                ('next_day_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
                'unique_together': {('user', 'date')},
            },
        ),
    ]
