# Generated by Django 6.0.5 on 2026-09-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_dailyreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
    ]
