# Generated by Django 5.1.15 on 2026-09-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_dailyreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='pay_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid (Loss of Pay)')], db_index=True, default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('paid', 'Annual Leave'), ('sick', 'Medical / Sick'), ('casual', 'Casual'), ('half_day', 'Half Day'), ('unpaid', 'Unpaid Leave (LOP)')], db_index=True, default='annual', max_length=20),
        ),
    ]
