# Generated by Django 6.0.5 on 2026-05-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', help_text='Default 3-letter currency code for the workspace.', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, help_text='Custom domain for the workspace.', max_length=255, null=True),
        ),
    ]
