# Generated by Django 6.0.5 on 2026-06-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_currency_company_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Disable tenant access when true')),
                ('allow_new_registrations', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=False)),
                ('enable_ai_features', models.BooleanField(default=True)),
                ('enable_custom_domains', models.BooleanField(default=False)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('support_email', models.EmailField(default='support@lumeo.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
