# Generated by Django 6.0.5 on 2026-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_address_line1_company_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_format',
            field=models.CharField(default='MMM DD, YYYY', help_text='Default date format for the workspace.', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='time_format',
            field=models.CharField(default='12h', help_text='12h or 24h time format.', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Default timezone for the workspace.', max_length=50),
        ),
    ]
