# Generated by Django 6.0.5 on 2026-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_date_format_company_time_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='paypal_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paypal_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
