# Generated by Django 6.0.5 on 2026-06-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_paypal_client_id_company_paypal_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(default='INV-', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(default='due_on_receipt', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='quote_prefix',
            field=models.CharField(default='QT-', max_length=20),
        ),
    ]
