# Generated by Django 6.0.5 on 2026-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_default_tax_rate_company_invoice_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_prefix',
            field=models.CharField(default='CTR-', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='default_contract_terms',
            field=models.TextField(blank=True, help_text='Default boilerplate terms for new contracts.', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='require_e_signature',
            field=models.BooleanField(default=True),
        ),
    ]
