# Generated by Django 6.0.5 on 2026-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_contract_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_label',
            field=models.CharField(blank=True, help_text='e.g. VAT, EIN, GST', max_length=50, null=True),
        ),
    ]
