# Generated by Django 6.0.5 on 2026-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_company_tax_id_company_tax_id_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_customer_portal_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_ticket_priority',
            field=models.CharField(default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='ticket_prefix',
            field=models.CharField(default='TCK-', max_length=20),
        ),
    ]
