# Generated by Django 6.0.5 on 2026-06-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_allow_customer_portal_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_project_view',
            field=models.CharField(default='list', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='project_prefix',
            field=models.CharField(default='PRJ-', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='require_project_approval',
            field=models.BooleanField(default=False),
        ),
    ]
