# Generated by Django 6.0.5 on 2026-06-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_default_project_view_company_project_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='late_mark_after_minutes',
            field=models.IntegerField(default=15, help_text='Minutes after start time to mark as late.'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_end_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_start_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
