# Generated by Django 6.0.5 on 2026-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_company_late_mark_after_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_half_day_leaves',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_leave_quota',
            field=models.IntegerField(default=20, help_text='Default annual leave quota.'),
        ),
        migrations.AddField(
            model_name='company',
            name='require_leave_approval',
            field=models.BooleanField(default=True),
        ),
    ]
