# Generated by Django 6.0.5 on 2026-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_company_allow_half_day_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_employee_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='default_new_user_role',
            field=models.CharField(default='employee', max_length=20),
        ),
    ]
