# Generated by Django 6.0.5 on 2026-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_allow_employee_invite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_lead_status',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='lead_assignment_round_robin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='lead_prefix',
            field=models.CharField(default='LD-', max_length=20),
        ),
    ]
