# Generated by Django 6.0.5 on 2026-06-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_company_default_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_manual_time_entry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_billable_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='require_time_log_approval',
            field=models.BooleanField(default=False),
        ),
    ]
