# Generated by Django 6.0.5 on 2026-06-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_allow_manual_time_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='task_allow_subtasks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='task_auto_assign_creator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='task_default_priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='task_require_due_date',
            field=models.BooleanField(default=False),
        ),
    ]
