# Generated by Django 6.0.5 on 2026-06-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_company_task_allow_subtasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='module_attendance_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_crm_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_events_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_finance_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_hr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_notice_board_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_projects_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='module_tickets_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
