# Generated by Django 6.0.5 on 2026-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_module_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_client_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='datatable_row_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_can_export_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(default='en', help_text='Default language.', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='need_admin_approval_after_client_signup',
            field=models.BooleanField(default=True),
        ),
    ]
