# Generated by Django 6.0.5 on 2026-06-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_company_allow_client_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='authorised_signatory_signature',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hsn_sac_code_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_due_after_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_logo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_other_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_terms',
            field=models.TextField(blank=True, default='Thank you for your business.'),
        ),
        migrations.AddField(
            model_name='company',
            name='send_reminder_after_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='company',
            name='send_reminder_before_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='show_authorised_signatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_company_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_project_on_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_status_on_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_tax_calculation_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_tax_number_on_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
