# Generated by Django 6.0.5 on 2026-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_authorised_signatory_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_template',
            field=models.CharField(default='template1', max_length=50),
        ),
    ]
