# Generated by Django 6.0.5 on 2026-06-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_language',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_logo',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_other_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_signatory_signature',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_template',
            field=models.CharField(default='template1', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='show_authorised_signatory_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='show_client_name_on_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='show_company_logo_on_contract',
            field=models.BooleanField(default=True),
        ),
    ]
