# Generated by Django 6.0.5 on 2026-06-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_contract_language_company_contract_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contract_language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contract_logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contract_other_information',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contract_signatory_signature',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contract_template',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_contract_terms',
        ),
        migrations.RemoveField(
            model_name='company',
            name='require_e_signature',
        ),
        migrations.RemoveField(
            model_name='company',
            name='show_authorised_signatory_on_contract',
        ),
        migrations.RemoveField(
            model_name='company',
            name='show_client_name_on_contract',
        ),
        migrations.RemoveField(
            model_name='company',
            name='show_company_logo_on_contract',
        ),
        migrations.AddField(
            model_name='company',
            name='contract_number_digits',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_number_separator',
            field=models.CharField(default='#', max_length=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='contract_prefix',
            field=models.CharField(default='CONT', max_length=20),
        ),
    ]
