# Generated by Django 6.0.5 on 2026-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_remove_company_contract_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='taxes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
