# Generated by Django 6.0.5 on 2026-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_company_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_agents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='ticket_visibility_setting',
            field=models.CharField(default='Global', max_length=50),
        ),
    ]
