# Generated by Django 6.0.5 on 2026-06-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_company_ticket_agents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
