# Generated by Django 6.0.5 on 2026-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_company_ticket_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
