# Generated by Django 6.0.5 on 2026-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_company_ticket_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_channels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
