# Generated by Django 6.0.5 on 2026-06-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_ticket_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_reply_templates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
