# Generated by Django 6.0.5 on 2026-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_company_ticket_reply_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticket_round_robin',
            field=models.BooleanField(default=False),
        ),
    ]
