# Generated by Django 6.0.5 on 2026-06-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_company_ticket_round_robin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project_send_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
