# Generated by Django 6.0.5 on 2026-06-20 06:59

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_company_project_send_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project_statuses',
            field=models.JSONField(blank=True, default=companies.models.default_project_statuses),
        ),
    ]
