# Generated by Django 6.0.5 on 2026-06-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_company_project_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='project_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
