# Generated by Django 6.0.5 on 2026-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_company_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='allow_clock_in_outside_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='allow_self_clock_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='allow_shift_change_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_reminder_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_clock_in_first_sign_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='clock_in_ip_address_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='clock_in_location_radius_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='email_report_role',
            field=models.CharField(default='App Administrator', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='save_clock_in_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='send_monthly_attendance_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='week_starts_from',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='late_mark_after_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
