# Generated by Django 6.0.5 on 2026-06-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0034_company_allow_clock_in_outside_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_shifts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
