# Generated by Django 6.0.5 on 2026-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0035_company_employee_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shift_rotations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
