# Generated by Django 6.0.5 on 2026-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_company_shift_rotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='leave_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
