# Generated by Django 6.0.5 on 2026-06-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0037_company_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='leave_count_from',
            field=models.CharField(default='joining_date', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='reporting_manager_leave_approval_role',
            field=models.CharField(default='Pre-Approve', max_length=20),
        ),
    ]
