# Generated by Django 6.0.5 on 2026-06-20 09:53

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_company_leave_count_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='roles',
            field=models.JSONField(blank=True, default=companies.models.default_roles),
        ),
    ]
