# Generated by Django 6.0.5 on 2026-06-22 07:43

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_company_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deal_agents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='deal_categories',
            field=models.JSONField(blank=True, default=companies.models.default_deal_categories),
        ),
        migrations.AddField(
            model_name='company',
            name='lead_pipelines',
            field=models.JSONField(blank=True, default=companies.models.default_lead_pipelines),
        ),
        migrations.AddField(
            model_name='company',
            name='lead_round_robin_agents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='lead_sources',
            field=models.JSONField(blank=True, default=companies.models.default_lead_sources),
        ),
    ]
