# Generated by Django 6.0.5 on 2026-06-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0040_company_deal_agents_company_deal_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='timelog_report_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='timelog_send_daily_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='timelog_send_tracker_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='timelog_stop_timer_after_shift',
            field=models.BooleanField(default=False),
        ),
    ]
