# Generated by Django 6.0.5 on 2026-06-22 08:13

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0041_company_timelog_report_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='task_board_default_length',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='task_client_visible_fields',
            field=models.JSONField(blank=True, default=companies.models.default_task_client_visible_fields),
        ),
        migrations.AddField(
            model_name='company',
            name='task_default_status_filter',
            field=models.CharField(default='incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='task_reminder_after_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='task_reminder_before_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='task_reminder_on_due_day',
            field=models.BooleanField(default=True),
        ),
    ]
