# Generated by Django 6.0.5 on 2026-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_company_task_board_default_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(default='support@crm.estgrp.in', max_length=254),
        ),
    ]
