# Generated by Django 6.0.5 on 2026-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0043_alter_platformsettings_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='automated_shifts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
