# Generated by Django 6.0.5 on 2026-07-08 06:49

import django.db.models.deletion
from django.db import migrations

def update_hr_roles(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    
    new_hr_perms = {
        "Clients": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Employees": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Projects": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Attendance": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Tasks": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Estimates": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Invoices": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Payments": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Time Logs": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Tickets": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Events": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Notices": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Leaves": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"},
        "Leads": {"Add": "All", "View": "All", "Update": "All", "Delete": "None"}
    }
    
    for company in Company.objects.all():
        roles = company.roles
        if not roles:
            continue
            
        updated = False
        for role in roles:
            if role.get('id') == 'hr':
                role['permissions'] = new_hr_perms
                updated = True
                break
                
        if updated:
            company.roles = roles
            company.save(update_fields=['roles'])

def revert_hr_roles(apps, schema_editor):
    pass # No easy reverse migration needed

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0044_company_automated_shifts'),
    ]

    operations = [
        migrations.RunPython(update_hr_roles, revert_hr_roles),
    ]
