# Generated by Django 6.0.5 on 2026-07-09 07:48

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0045_update_hr_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='weekend_policy',
            field=models.JSONField(blank=True, default=companies.models.default_weekend_policy),
        ),
    ]
