# Generated by Django 6.0.5 on 2026-07-10 12:56

from django.db import migrations


def remove_saturday_from_weekend_policy(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        if not company.weekend_policy:
            continue
        policy = company.weekend_policy
        # Check if saturday is in the policy
        if "5" in policy and policy["5"]:
            # Check if it equals the old default ["all"] and they haven't explicitly set something else
            if policy["5"] == ["all"]:
                policy["5"] = []
                company.save(update_fields=["weekend_policy"])

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0046_company_weekend_policy'),
    ]

    operations = [
        migrations.RunPython(remove_saturday_from_weekend_policy, reverse_code=migrations.RunPython.noop),
    ]
