# Generated by Django 6.0.5 on 2026-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_remove_saturday_weekend_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='late_grace_period_minutes',
            field=models.IntegerField(default=15, help_text='Grace period before marking as Late'),
        ),
        migrations.AddField(
            model_name='company',
            name='shift_end_time',
            field=models.TimeField(default='18:00:00', help_text='Default shift end time'),
        ),
        migrations.AddField(
            model_name='company',
            name='shift_start_time',
            field=models.TimeField(default='09:30:00', help_text='Default shift start time'),
        ),
    ]
