# Generated by Django 6.0.5 on 2026-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0048_company_late_grace_period_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
