# Generated by Django 6.0.5 on 2026-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0049_company_custom_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
