# Generated by Django 6.0.5 on 2026-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0050_company_razorpay_key_id_company_razorpay_key_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Public email address of the company', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_website',
            field=models.URLField(blank=True, help_text='Public website of the company', max_length=255, null=True),
        ),
    ]
