# Generated by Django 6.0.5 on 2026-07-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0051_company_company_email_company_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invoice_due_after_days', models.PositiveIntegerField(default=15)),
                ('language', models.CharField(default='en', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_separator', models.CharField(default='-', max_length=5)),
                ('invoice_digits', models.PositiveIntegerField(default=5)),
                ('credit_note_prefix', models.CharField(default='CN', max_length=20)),
                ('credit_note_separator', models.CharField(default='-', max_length=5)),
                ('credit_note_digits', models.PositiveIntegerField(default=5)),
                ('estimate_prefix', models.CharField(default='EST', max_length=20)),
                ('estimate_separator', models.CharField(default='-', max_length=5)),
                ('estimate_digits', models.PositiveIntegerField(default=5)),
                ('estimate_request_prefix', models.CharField(default='ESTREQ', max_length=20)),
                ('estimate_request_separator', models.CharField(default='-', max_length=5)),
                ('estimate_request_digits', models.PositiveIntegerField(default=5)),
                ('order_prefix', models.CharField(default='ORD', max_length=20)),
                ('order_separator', models.CharField(default='-', max_length=5)),
                ('order_digits', models.PositiveIntegerField(default=5)),
                ('proposal_prefix', models.CharField(default='PROP', max_length=20)),
                ('proposal_separator', models.CharField(default='-', max_length=5)),
                ('proposal_digits', models.PositiveIntegerField(default=5)),
                ('template_id', models.CharField(default='template_1', max_length=50)),
                ('show_client_name', models.BooleanField(default=True)),
                ('show_client_email', models.BooleanField(default=True)),
                ('show_client_phone', models.BooleanField(default=True)),
                ('show_client_company_name', models.BooleanField(default=True)),
                ('show_client_address', models.BooleanField(default=True)),
                ('show_project_on_invoice', models.BooleanField(default=True)),
                ('show_sender_tax_number', models.BooleanField(default=False)),
                ('show_receiver_tax_number', models.BooleanField(default=False)),
                ('show_hsn_sac_code', models.BooleanField(default=False)),
                ('show_status_on_invoice', models.BooleanField(default=True)),
                ('show_tax_calculation_message', models.BooleanField(default=False)),
                ('show_authorised_signatory', models.BooleanField(default=False)),
                ('authorised_signatory_signature', models.URLField(blank=True, max_length=512, null=True)),
                ('invoice_logo', models.URLField(blank=True, max_length=512, null=True)),
                ('invoice_terms', models.TextField(blank=True, default='Thank you for your business.')),
                ('invoice_other_information', models.TextField(blank=True, null=True)),
                ('send_reminder_before_days', models.PositiveIntegerField(default=0)),
                ('send_reminder_after_days', models.PositiveIntegerField(default=3)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('qr_code', models.URLField(blank=True, max_length=512, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='companies.company')),
            ],
        ),
    ]
