# Generated by Django 6.0.5 on 2026-07-24 04:45

from django.db import migrations


def migrate_data(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    InvoiceSettings = apps.get_model('companies', 'InvoiceSettings')
    
    for company in Company.objects.all():
        InvoiceSettings.objects.create(
            company=company,
            default_tax_rate=company.default_tax_rate,
            invoice_due_after_days=company.invoice_due_after_days,
            language=company.invoice_language,
            currency=company.currency,
            
            invoice_prefix=company.invoice_prefix,
            
            template_id=company.invoice_template,
            
            show_client_name=company.show_client_name,
            show_client_email=company.show_client_email,
            show_client_phone=company.show_client_phone,
            show_client_company_name=company.show_client_company_name,
            show_client_address=company.show_client_address,
            show_project_on_invoice=company.show_project_on_invoice,
            
            show_sender_tax_number=company.show_tax_number_on_invoice,
            show_hsn_sac_code=company.hsn_sac_code_show,
            show_tax_calculation_message=company.show_tax_calculation_message,
            show_status_on_invoice=company.show_status_on_invoice,
            show_authorised_signatory=company.show_authorised_signatory,
            
            authorised_signatory_signature=company.authorised_signatory_signature,
            invoice_logo=company.invoice_logo,
            
            invoice_terms=company.invoice_terms,
            invoice_other_information=company.invoice_other_information,
            
            send_reminder_before_days=company.send_reminder_before_days,
            send_reminder_after_days=company.send_reminder_after_days,
        )

def reverse_migrate_data(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    InvoiceSettings = apps.get_model('companies', 'InvoiceSettings')
    
    for settings in InvoiceSettings.objects.all():
        company = settings.company
        company.default_tax_rate = settings.default_tax_rate
        company.invoice_due_after_days = settings.invoice_due_after_days
        company.invoice_language = settings.language
        company.currency = settings.currency
        company.invoice_prefix = settings.invoice_prefix
        company.invoice_template = settings.template_id
        company.show_client_name = settings.show_client_name
        company.show_client_email = settings.show_client_email
        company.show_client_phone = settings.show_client_phone
        company.show_client_company_name = settings.show_client_company_name
        company.show_client_address = settings.show_client_address
        company.show_project_on_invoice = settings.show_project_on_invoice
        company.show_tax_number_on_invoice = settings.show_sender_tax_number
        company.hsn_sac_code_show = settings.show_hsn_sac_code
        company.show_tax_calculation_message = settings.show_tax_calculation_message
        company.show_status_on_invoice = settings.show_status_on_invoice
        company.show_authorised_signatory = settings.show_authorised_signatory
        company.authorised_signatory_signature = settings.authorised_signatory_signature
        company.invoice_logo = settings.invoice_logo
        company.invoice_terms = settings.invoice_terms
        company.invoice_other_information = settings.invoice_other_information
        company.send_reminder_before_days = settings.send_reminder_before_days
        company.send_reminder_after_days = settings.send_reminder_after_days
        company.save()

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0052_add_invoice_settings'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_migrate_data),
    ]
