# Generated by Django 6.0.5 on 2026-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0054_remove_old_invoice_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='quickbooks_sync_status',
            field=models.BooleanField(default=False),
        ),
    ]
