# Generated by Django 6.0.5 on 2026-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0055_invoicesettings_quickbooks_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='bank_routing_number',
            field=models.CharField(blank=True, help_text='Routing / Sort Code / SWIFT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Company Registration Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='VAT / Tax ID for the company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='footer_text',
            field=models.TextField(blank=True, default='Thank you for your business.'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='template_accent_color',
            field=models.CharField(default='#4F46E5', help_text='Hex code for template accent', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='template_font_family',
            field=models.CharField(default='Inter', help_text='Primary font family', max_length=50),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='template_scale',
            field=models.CharField(default='Standard', help_text='Font scaling: Small, Standard, Large', max_length=20),
        ),
    ]
