# Generated by Django 6.0.5 on 2026-07-30 11:33

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0056_invoicesettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deal_pipelines',
            field=models.JSONField(blank=True, default=companies.models.default_deal_pipelines),
        ),
    ]
