# Generated by Django 6.0.5 on 2026-07-30 11:54

from django.db import migrations


def sync_deal_pipelines(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        if company.lead_pipelines:
            company.deal_pipelines = company.lead_pipelines
            company.save(update_fields=['deal_pipelines'])

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0057_company_deal_pipelines'),
    ]

    operations = [
        migrations.RunPython(sync_deal_pipelines, migrations.RunPython.noop),
    ]
