# Generated by Django 6.0.5 on 2026-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0058_sync_deal_pipelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='purchase_order_delivery_address',
            field=models.TextField(blank=True, help_text='Default delivery address for POs', null=True),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='purchase_order_digits',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='purchase_order_prefix',
            field=models.CharField(default='PO', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='purchase_order_separator',
            field=models.CharField(default='-', max_length=5),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='purchase_order_terms',
            field=models.TextField(blank=True, default='Please supply the items listed above.'),
        ),
    ]
