# Generated by Django 6.0.5 on 2026-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0059_invoicesettings_purchase_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='bill_digits',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='bill_prefix',
            field=models.CharField(default='BILL', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='bill_separator',
            field=models.CharField(default='-', max_length=5),
        ),
    ]
