# Generated by Django 6.0.5 on 2026-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0060_invoicesettings_bill_digits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, help_text='Meta System User Access Token', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_business_account_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='WhatsApp Phone Number ID', max_length=255, null=True),
        ),
    ]
